# Generated by Django 4.2.3 on 2023-10-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_product_related_images_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="related_images",
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
