# Generated by Django 4.2.3 on 2023-10-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_product_related_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="related_images",
        ),
    ]
