# Generated by Django 4.2.3 on 2023-10-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="category/"),
        ),
    ]
